import scrapy

class SquashGearSpider(scrapy.Spider):
    name = "squashgear"
    start_urls = [
        #'http://squashgear.com/new.html',
        'http://www.squashgear.com/dunlop.html',
        'http://www.squashgear.com/headracquets1.html',
        'http://www.squashgear.com/prince-squash-rackets.html',
        'http://www.squashgear.com/wilsonracquets.html',
        'http://www.squashgear.com/harrow.html',
        'http://www.squashgear.com/blacknigrac.html',
        'http://www.squashgear.com/eyerackets.html',
        'http://www.squashgear.com/tesqra1.html',
        'http://www.squashgear.com/karrac.html',
        'http://www.squashgear.com/mantaracquets.html',
        'http://www.squashgear.com/salmingrackets.html',
        'http://www.squashgear.com/un.html',
        #'http://www.squashgear.com/clforbe.html',
        #'http://www.squashgear.com/indoor-court-shoes-closeouts-clearance.html'
        'http://www.squashgear.com/salming.html',
        'http://www.squashgear.com/rockets123.html',
        #'http://www.squashgear.com/asicsshoes.html',
        'http://www.squashgear.com/asicstactic.html',
        'http://www.squashgear.com/dodore.html',
        'http://www.squashgear.com/blast.html',
        'http://www.squashgear.com/as.html',
        'http://www.squashgear.com/senseinupcourt.html',
        'http://www.squashgear.com/flashpoints.html',
        'http://www.squashgear.com/upcourt.html',
        'http://www.squashgear.com/as1.html',
        'http://www.squashgear.com/blade.html',
        'http://www.squashgear.com/eyeshoes.html',
        'http://www.squashgear.com/adidas.html',
        'http://www.squashgear.com/dunlopshoes.html',
        'http://www.squashgear.com/headshoes.html',
        'http://www.squashgear.com/harrowshoes.html',
        'http://www.squashgear.com/wilsonshoes.html',
        'http://www.squashgear.com/princeshoes1.html',
        'http://www.squashgear.com/hitecshoes.html',
        'http://www.squashgear.com/yonexshoes.html',
        #'http://www.squashgear.com/shoesforkids.html',
        #'http://www.squashgear.com/runningshoes.html',
        #'http://www.squashgear.com/womensshoes.html',
        'http://www.squashgear.com/squashballs1.html',
        #'http://www.squashgear.com/strings.html',
        'http://www.squashgear.com/ashawaystrings.html,'
        'http://www.squashgear.com/test1.html',
        'http://www.squashgear.com/ey.html',
        'http://www.squashgear.com/princestrings.html',
        'http://www.squashgear.com/dunlopstrings.html',
        'http://www.squashgear.com/wilsonstrings.html',
        'http://www.squashgear.com/karakalstrings1.html',
        'http://www.squashgear.com/luxilon.html',
        'http://www.squashgear.com/headstrings1.html',
        'http://www.squashgear.com/salmingstrings.html',
        #'http://www.squashgear.com/repgrom.html',
        'http://www.squashgear.com/racgripandhe.html',
        #'http://www.squashgear.com/eyeweargoggles.html',
        'http://www.squashgear.com/wilsongoggles.html',
        'http://www.squashgear.com/prandekgo.html',
        'http://www.squashgear.com/headgoggles.html',
        'http://www.squashgear.com/swgoggles.html',
        'http://www.squashgear.com/haruprgo.html',
        'http://www.squashgear.com/dunlopgoggles.html',
        'http://www.squashgear.com/blkngo.html',
        'http://www.squashgear.com/tego.html',
        'http://www.squashgear.com/salminggoogles.html',
        'http://www.squashgear.com/spgo.html',
        'http://www.squashgear.com/regr.html',
        #'http://www.squashgear.com/shoesinsoles.html',
        #'http://www.squashgear.com/bandsbandanas.html',
        #'http://www.squashgear.com/sportsocks.html',
        #'http://www.squashgear.com/sportbags1.html',
        'http://www.squashgear.com/dunlopbags.html',
        'http://www.squashgear.com/headbags.html,',
        'http://www.squashgear.com/tecnifibrebags.html',
        'http://www.squashgear.com/princebags.html',
        'http://www.squashgear.com/wilsonbags.html',
        'http://www.squashgear.com/karakalbags.html',
        'http://www.squashgear.com/harrowbags.html',
        'http://www.squashgear.com/blknba.html',
        'http://www.squashgear.com/eyeracketsbags.html',
        'http://www.squashgear.com/salmingbags.html',
        'http://www.squashgear.com/adidasbags.html',
        #'http://www.squashgear.com/squashapparel.html',
        #'http://www.squashgear.com/salmingapparel.html',
    ]

    def parse(self, response):
        for item in response.css('.name'):
            yield {
                'aff_url': response.urljoin(item.css('a::attr(href)').extract_first()),
                'aff_title': item.css('a::text').extract_first(),
            }
